name: List Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group Name'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  list-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-cli@v1

      - name: Login to Azure
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: List Azure Resources
        run: |
          az login --identity
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az resource list --resource-group ${{ github.event.inputs.resource_group_name }} --output table

      - name: Log resource list to summary
        run: |
          resourceGroup=${{ github.event.inputs.resource_group_name }}
          az login --identity
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az resource list --resource-group $resourceGroup --output table >> $env:GITHUB_STEP_SUMMARY
