name: List Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group Name'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  list-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        id: login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: List Azure Resources
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
              $resourceGroupName = "dlpm-kry025-rg" `    
              echo $resourceGroupName `
              # List resources in the specified resource group `
              $resources = Get-AzResource -ResourceGroupName $resourceGroupName `
              $resources | Format-Table `    
              # Log resource list to summary `
              $resources | Format-Table | Out-String | ForEach-Object { Write-Output "## $_" } >> $env:GITHUB_STEP_SUMMARY
